version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.prysm-ropsten.public.dappnode.eth:0.1.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.3-rc.2
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "13000"
      - 12000/udp
    restart: unless-stopped
    environment:
      HTTP_WEB3PROVIDER: "http://ropsten.dappnode:8545"
      CORSDOMAIN: "http://prysm-ropsten.dappnode"
      EXTRA_OPTS: ""
  validator:
    image: "validator.prysm-ropsten.public.dappnode.eth:0.1.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.3-rc.2
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.prysm-ropsten.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-roopsten.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
